// Include valid commands in the loader

#include "commands/cp.c"
#include "commands/rm.c"
#include "commands/cd.c"
#include "commands/dir.c"
#include "commands/ls_integrate.c"
#include "commands/printenv.c"
#include "commands/apropos_integrate.c"
#include "commands/chmod_integrate.c"
#include "commands/clear_integrate.c"
#include "commands/date_integrate.c"
#include "commands/echo_integrate.c"
#include "commands/gzip_integrate.c"
#include "commands/mkdir_integrate.c"
#include "commands/sleep_integrate.c"
#include "commands/sort_integrate.c"
#include "commands/time_integrate.c"
#include "commands/uname_integrate.c"
#include "commands/umask_integrate.c"
#include "commands/whatis_integrate.c"
#include "commands/zcat_integrate.c"
